### ISSUE TITLE
Feature request: Sync board directory with directory on computer, and then run main.py

### ISSUE THREAD

**Issue by tychop** [adafruit/ampy#22]
Isn't this what would make life easier?
When you're done coding, run a command to sync the directory with all it's subdirs & files and run it?
Or maybe just delete everything and copy over a complete directory structure and run main?

**Comment by tychop** [comment]
I managed it by scripting ampy in bash....

**Comment by jonaslorander** [comment]
Would you possibly want to share that code, in say a gist?

**Comment by tychop** [comment]
Sure, I just need to generalize it so everybody can use it. I'll drop a link here when it's ready.

**Comment by jonaslorander** [comment]
Great, thanks!

**Comment by tychop** [comment]
Here it is..
call it with -c if you want to clean out the microcontroller before copying your files...
https://gist.github.com/tychop/29bd4af2b5492d55623b2754a2f37208

**Comment by jonaslorander** [comment]
Thank you! That will be very useful!
