### ISSUE TITLE
some functions import uos - does not work for CircutPython 2.0.0-beta-1.1

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/ampy#24]
CircuitPython 2.0.0-beta-1.1 doe not include uos (only os ).
Several functions - rm, ls,mkdir etc  try to import uos and fail.

**Comment by tannewt** [comment]
I opened https://github.com/adafruit/ampy/pull/26 with a fix.

**Comment by jerryneedell** [comment]
I downloaded an tried your fix and it works for me! Thanks!

**Comment by dhalbert** [comment]
Fixed by #26. Uploaded to pypi as https://pypi.python.org/pypi/adafruit-ampy/1.0.2 Uninstalled my local copy, installed it via pip. Tested on Cpy 1.0.0 and 2.0.0 and it works on both.
