### ISSUE TITLE
Ampy tries to work while picocom is open

### ISSUE THREAD

**Issue by Cediddi** [adafruit/ampy#30]
I think ampy should check if port is being used and if it is, raise an error. A simple approach would be using fuser to check if any process is holding the file descriptor.

**Comment by tdicola** [comment]
Thanks for the suggestion!  Let's move this to a potential future feature.  Fuser is handy but wouldn't be available on windows so need to look for cross plat solutions there.

**Comment by Cediddi** [comment]
Fuser wouldn't fit to all linux environments either. I may look at a alternative way, maybe psutil and pyserial together would work.

**Comment by ladyada** [comment]
Hiya! We are discontinuing support for ampy, and will no longer be maintaining it. We are leaving this repository available for continued use. If you would like to take over supporting it, please contact us on the Adafruit Discord server and we can transfer the repository to you.
If you wish to continue developing it on your own, please fork the repository.
