### ISSUE TITLE
put get status

### ISSUE THREAD

**Issue by Cediddi** [adafruit/ampy#31]
I think this is trivial if we use tqdm. When putting or getting a single file we can show transferred bytes. When uploading a folder, we can show transferred files. This would be very cool. Can send PR.

**Comment by tdicola** [comment]
Nice idea!  I'll put this under future enhancements that might be added later.  Thanks!

**Comment by ladyada** [comment]
Hiya! We are discontinuing support for ampy, and will no longer be maintaining it. We are leaving this repository available for continued use. If you would like to take over supporting it, please contact us on the Adafruit Discord server and we can transfer the repository to you.
If you wish to continue developing it on your own, please fork the repository.
