### ISSUE TITLE
Can not run twice for ESP32

### ISSUE THREAD

**Issue by iascchen** [adafruit/ampy#41]
When I use it on my MAC OS, I found it will be hanged when i run `ampy --port /dev/tty.SLAB_USBtoUART ls` in second time. If I want to use it again, I have to replug usb cable.

I used the ampy 1.0.3 version, and micropython firmware of esp32-20180302-v1.9.3-386-g9884a2c7.bin, python version is 3.6.4

<img width="606" alt="default" src="https://user-images.githubusercontent.com/3230939/36885725-ae3d046c-1e23-11e8-932e-5e89a71340e7.png">

`  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ampy/cli.py", line 147, in ls
    for f in board_files.ls(directory):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ampy/files.py", line 94, in ls
    self._pyboard.enter_raw_repl()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ampy/pyboard.py", line 192, in enter_raw_repl
    raise PyboardError('could not enter raw repl')
ampy.pyboard.PyboardError: could not enter raw repl
`

I checked the source code of micropython, and think may be the issue caused by it firmware code in ports/esp32/main.c

`
    for (;;) {
        if (pyexec_mode_kind == PYEXEC_MODE_RAW_REPL) {
            if (pyexec_raw_repl() != 0) {
                break;
            }
        } else {
            if (pyexec_friendly_repl() != 0) {
                break;
            }
        }
    }
`

**Comment by hutualive** [comment]
I have similar issue on mac but not linux(debian). I checked the code mentioned in ports/esp32/main.c, seems it's a standard implementation cross different Arch/MCUs, so better figure out a walk-around on pyboard.py alone.

**Comment by hyansuper** [comment]
I have the same issue, I am using Ubuntu

**Comment by Tomekske** [comment]
Use the option '-d 0.5' in every command.
e.g.: ampy -p COM5 -d 0.5 ls or ampy -p COM5 -d 0.5 put file.py

**Comment by ladyada** [comment]
Hiya! We are discontinuing support for ampy, and will no longer be maintaining it. We are leaving this repository available for continued use. If you would like to take over supporting it, please contact us on the Adafruit Discord server and we can transfer the repository to you.
If you wish to continue developing it on your own, please fork the repository.

**Comment by scientist1642** [comment]
or if `-d 0.5` doesn't work use `-d 1` from Mac.
