### ISSUE TITLE
Ampy is install yet linux indicates command not found.

### ISSUE THREAD

**Issue by qwerty12345asdf** [adafruit/ampy#49]
I am trying to access my nodemcu file system using the ampy tool by trying to follow this guide.
I have run into the following problem even after installing ampy the system simply wont allow me to use it says ampy not installed.
Hope you can help me I have attached a screen-shot of the method i used to install and verify if ampy was installed or not.
![screenshot from 2018-06-15 13-14-57](https://user-images.githubusercontent.com/23262485/41456766-19fe8c52-709f-11e8-80c8-38d6b7ce905b.png)

**Comment by qwerty12345asdf** [comment]
The guide i used was https://cdn-learn.adafruit.com/downloads/pdf/micropython-basics-load-files-and-run-code.pdf

**Comment by qwerty12345asdf** [comment]
used git sorry for the trouble :)

**Comment by IO42630** [comment]
Thank you for the hint. This fixed the issue for me:

`pip3 install --upgrade git+https://github.com/adafruit/ampy`

The `README.md`  is a bit misleading.
