### ISSUE TITLE
error uploading _odroid_go_ package

### ISSUE THREAD

**Issue by danielhrisca** [adafruit/ampy#58]
#### Environment
Windows 10 x64
ampy 1.0.5
Python 3.6 x86

#### Description
I've tried to upload the _odroid_go_ package using this command (the package was uncompressed prior)

```
ampy -p COM7 -b 115200 put odroid_go
``` 

If I list the odroid_go folder on the device I get this:

```python
['odroid_go.py', '__init__.py', 'examples', 'examples\x08attery', 'examples\x08utton', 'examples\\hello_world', 'examples\\led', 'examples\\led_pwm', 'examples\\speaker', 'utils', 'utils\x08attery', 'utils\x08utton', 'utils\\lcd', 'utils\\speaker']
```

**Comment by ladyada** [comment]
Hiya! We are discontinuing support for ampy, and will no longer be maintaining it. We are leaving this repository available for continued use. If you would like to take over supporting it, please contact us on the Adafruit Discord server and we can transfer the repository to you.
If you wish to continue developing it on your own, please fork the repository.
