### ISSUE TITLE
Esp8266 for Micropython on Windows 10 exception

### ISSUE THREAD

**Issue by Walkline80** [adafruit/ampy#63]
I'm using PyCharm with Micropython plugin to programming on Esp8266, I made a folder 'drivers' in the root path, and drag 2 files into it, when I upload files to Esp8266, the first file in 'drivers' will upload success, but, the second file will thrown exception at all.

here is the output

> Traceback (most recent call last):
  File "C:\Users\walkl\.PyCharmCE2018.2\config\plugins\intellij-micropython/scripts/microupload.py", line 138, in <module>
    main(sys.argv[1:])
  File "C:\Users\walkl\.PyCharmCE2018.2\config\plugins\intellij-micropython/scripts/microupload.py", line 79, in main
    files.put(remote_path, fd.read())
  File "C:\Python3\lib\site-packages\ampy\files.py", line 158, in put
    self._pyboard.exec_("f = open('{0}', 'wb')".format(filename))
  File "C:\Python3\lib\site-packages\ampy\pyboard.py", line 266, in exec_
    raise PyboardError('exception', ret, ret_err)
ampy.pyboard.PyboardError: ('exception', b'', b'Traceback (most recent call last):\r\n  File "<stdin>", line 1, in <module>\r\nOSError: [Errno 13] EACCES\r\n')

if I put all my flies in the root, upload will all success, how can I fix this bug?

adafruit-ampy: 1.0.5
Micropython for Esp8266 fireware: esp8266-20180511-v1.9.4.bin
PyCharm: Community 2018.2
Micropython plugin for PyCharm: 1.0.9

I'm a begginer, so I think all of those software & fireware are newest at this time

Please help me, thanks~

**Comment by Walkline80** [comment]
anyone can help me?
I have found what the problem is, but I still need your help!!!

in my case, there's a subfolder in the project root, drivers or any name, a python file in drivers named relay.py, when I upload project to esp8266 will thrown an exception EACCES

 here is my solution.....just rename the relay.py to any, just like myrelay.py, that's all.......

wtf? and why??

**Comment by yurikleb** [comment]
Try updating ampy to the new version 1.0.7 via pip3 (just released today), I also had problems working with subfolders on an ESP32 with ampy 1.0.5, but it works well now.

**Comment by Walkline80** [comment]
well, last version of ampy......the exception just like before

**Comment by ladyada** [comment]
Hiya! We are discontinuing support for ampy, and will no longer be maintaining it. We are leaving this repository available for continued use. If you would like to take over supporting it, please contact us on the Adafruit Discord server and we can transfer the repository to you.
If you wish to continue developing it on your own, please fork the repository.
