### ISSUE TITLE
AttributeError: module 'click' has no attribute 'group'

### ISSUE THREAD

**Issue by Merlin04** [adafruit/ampy#8]
I installed ampy with 
`sudo pip3 install adafruit-ampy`
When I run it, it produces this error:

$ ampy --help

Traceback (most recent call last):
  File "/usr/local/bin/ampy", line 7, in <module>
    from ampy.cli import cli
  File "/usr/local/lib/python3.5/dist-packages/ampy/cli.py", line 34, in \<module\>
    @click.group()
AttributeError: module 'click' has no attribute 'group'

**Comment by tdicola** [comment]
You might have an old version of the click framework installed, try forcing an upgrade to the latest version by running:
```
pip3 install --upgrade --force-reinstall click
```
